### ISSUE TITLE
Enable the wiki

### ISSUE THREAD

**Issue by movitto** [ManageIQ/virtfs#16]
I made t3h 4wes0me i/\\/\\4ge, need someplace to put it!

![arch](https://cloud.githubusercontent.com/assets/166845/22394023/b540a064-e4e2-11e6-97fb-7e9b999a67a8.png)

![arch](https://cloud.githubusercontent.com/assets/166845/22568853/4dd6e75a-e963-11e6-8ae8-7524b410f664.png)

**Comment by movitto** [comment]
@roliveri who has permissions to enable the wiki?

**Comment by roliveri** [comment]
@movitto 
I just created the initial wiki page. I'm not sure if that's enough. Take a look and see if you can update it.

**Comment by movitto** [comment]
Verified, thanks
